RA-03
kostyasmirnov/AndroidSprint_RecipeApp pull request #1
Opened 2023-12-30 12:13 UTC by kostyasmirnov

В самом конце вспомнил что забыл сделать размер иконки на кнопке "Избранное". Добавил атрибут `app:iconSize="24dp"`, и кнопка избранное стало больше... 
Не смог понять как это исправит, прошу помочь

2023-12-31 00:55 UTC, ievetrov requested changes

2023-12-31 00:55 UTC, ievetrov commented on app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/button1"
Предлагаю давать более релевантные названия айдишникам, указывая, что это элемент кнопки и для чего он нужен. Кроме того индексы использовать не лучшая практика. Давай доработаем. Например, btnCategories

2023-12-31 00:55 UTC, ievetrov commented on app/src/main/res/values/style.xml
> +        <item name="android:textAppearance">@style/StyleTitle14</item>
смотри, этот стиль с регулар шрифтом перебивает то, что ниже прописал айтем с montserrat_alternates_medium. поэтому кнопки отображаются с тонким регулар шрифтом

2023-12-31 00:55 UTC, ievetrov commented on app/src/main/res/values/style.xml
> +        <item name="android:textStyle">bold</item>
а этот элемент ни на что не влияет, тк вся необходимая толщина хранится в импортируемом шрифте

2023-12-31 00:55 UTC, ievetrov commented on app/src/main/res/layout/activity_main.xml
> +            app:iconSize="24dp" />
изначально ты импортировал иконку с нужным размером. как и в макете она такого же размера как текст. из-за повторного перемасштабирования картинка меняет свой размер.

2023-12-31 00:55 UTC, ievetrov commented on app/src/main/res/values/themes.xml
> +        <item name="fontFamily">@font/montserrat_alternates_regular</item>
а чемуты решил такой шрифт задать для всего приложения?

2024-01-01 11:32 UTC, kostyasmirnov commented
fix: 
- added relevant names for ids
- changed the style for **StyleNavButton**
- delete `textStyle>bold<` in style **StyleNavButton**
- delete `StyleNavButton` in **btnFavorites**
- delete font from `themes.xml`

2024-01-04 14:24 UTC, ievetrov requested changes

2024-01-04 14:24 UTC, ievetrov commented on app/src/main/res/layout/activity_main.xml
> +            android:text="Избранное"
Текст на кнопках не вынесен в текстовые ресурсы

2024-01-04 14:24 UTC, ievetrov commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginStart="@dimen/main_padding"
Не обязательно для каждой стороны прописывать марджины по отдельности. Есть более универсальные атрибуты. 
android:layout_margin=""
android:layout_marginHorizontal=""
android:layout_marginVertical=""

2024-01-04 14:24 UTC, ievetrov commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/bottomButtons"
Предлагаю еще чуть более точно указать в айдишнике для чего он нужен, чтобы в коде потом проще было ориентироваться. Можно добавить в качестве префикса `layout...`

2024-01-04 14:24 UTC, ievetrov commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintBottom_toBottomOf="parent">
Констрейнты корректнее задавать минимум на 2 оси. В данном случае рекомендую к твоему нижнему констрейнту добавить еще по бокам. От элемента к родителю.

2024-01-04 14:24 UTC, ievetrov commented on app/src/main/res/values/style.xml
> +        <item name="fontFamily">@font/montserrat_alternates_regular</item>
А где еще используется regular шрифт? Ну то есть какое предназначение у него тут?

2024-01-04 14:24 UTC, ievetrov commented on app/src/main/res/values/style.xml
> +        <item name="android:textSize">14sp</item>
создание `StyleTitle14` было как раз для того, чтобы не дублировать тут значения толщины и размера шрифта. В названии стиля не случайно фигурирует `Title` - это значит, что таким шрифтом будут помечаться все заголовки. А они у нас преимущественно `SemiBold`.

Предлагаю из данного стиля кнопок убрать размер и толщину (которая medium и не соответствует макету). Затем отнаследоваться от StyleTitle14, где уже нужные есть толщина и размер шрифта.

2024-01-04 15:16 UTC, kostyasmirnov commented
fix: 
- texts on buttons are moved to text resources
- added universal attribute `android:layout_marginHorizontal="@dimen/main_padding"`
- renamed id layout
- added constraints left and right
- del font `montserrat_alternates_regular` from project
- del `textSize` and `fontFamily` from `StyleNavButton`

2024-01-05 10:38 UTC, ievetrov approved these changes

2024-01-05 17:27 UTC, merged