RA-13. implementation of a recipe screen without an ingredient counti…
kostyasmirnov/AndroidSprint_RecipeApp pull request #11
Opened 2024-02-03 07:09 UTC by kostyasmirnov

…ng mechanism

2024-02-04 12:47 UTC, ievetrov requested changes
Хорошо, надо чуть доработать.

По стилизации - обрати внимание на соответствие вертикальных отступов на экране, шрифтов и отступов горизонтального разделителя по бокам

2024-02-04 12:47 UTC, ievetrov commented on app/src/main/java/com/practicum/androidsprint/RecipeFragment.kt
> +        initIngredientsRecycler(recipeParcelable)
В целом ничего страшного нет, чтобы заинитить ресайклеры в одном методе. Тем более в будущем будем объединять все в один метод при подключении наблюдателя за стейтом

2024-02-04 12:47 UTC, ievetrov commented on app/src/main/java/com/practicum/androidsprint/MethodAdapter.kt
> +            .inflate(R.layout.item_method, viewGroup, false) // хз что тут вместо item_recipe
а в чем коммент? во вьюхолдере инициализируется элемент разметки, в который будут байндиться элементы из списка данных.

2024-02-04 12:47 UTC, ievetrov commented on app/src/main/java/com/practicum/androidsprint/MethodAdapter.kt
> +        methodDescription.text = "$index. ${dataSet[position]}"
Можно так, можно отдельным вью. Но так компактнее

2024-02-04 12:47 UTC, ievetrov commented on app/src/main/java/com/practicum/androidsprint/MethodAdapter.kt
> +        methodDescription.textSize = 14F
Не вижу необходимости принудительно задавать размер текста, предлагаю во вью использовать соответствующие стили в атрибутах

2024-02-04 12:47 UTC, ievetrov commented on app/src/main/java/com/practicum/androidsprint/RecipesListFragment.kt
>          val fragment = context
осталась лишняя переменная, можно получать контекст сразу через проперти

2024-02-04 12:47 UTC, ievetrov commented on app/src/main/res/layout/fragment_recipe.xml
> +        <TextView
Если текст будет слишком большой, то может располагаться вплотную к правой границе или вовсе вылезет за пределы экрана. Так как мы находимся внутри констрейнта, есть пара хитрых атрибутов, чтобы это реализовать более элегантно
app:layout_constrainedWidth="true"
app:layout_constraintHorizontal_bias="0.0"

2024-02-04 12:47 UTC, ievetrov commented on app/src/main/java/com/practicum/androidsprint/IngredientsAdapter.kt
> +        try {
Вообще трай кач мы использовали для обращения к ассетам, именно при создании инпутстрима. сейчас этот блок уже можно опустить

2024-02-04 13:15 UTC, kostyasmirnov commented on app/src/main/java/com/practicum/androidsprint/MethodAdapter.kt
> +            .inflate(R.layout.item_method, viewGroup, false) // хз что тут вместо item_recipe
забыл удалить

2024-02-04 16:56 UTC, kostyasmirnov commented
По стилизации вроде все ок, проверил шрифты и отступы

2024-02-04 19:07 UTC, ievetrov requested changes
Также дивайдер не касается границ вью и отличается по цвету

<img width="295" alt="Снимок экрана 2024-02-04 в 22 06 46" src="https://github.com/kostyasmirnov/AndroidSprint_RecipeApp/assets/34489023/37dc5853-bd95-49b2-8123-02f07c24cf30">

2024-02-04 19:07 UTC, ievetrov commented on app/src/main/res/layout/item_ingredient.xml
> +    <TextView
- Шрифт отличается от макета

2024-02-04 19:07 UTC, ievetrov commented on app/src/main/res/layout/item_ingredient.xml
> +        android:textAllCaps="true"
Не вынесен стиль со всеми необходимыми атрибутами

2024-02-04 19:07 UTC, ievetrov commented on app/src/main/res/layout/item_ingredient.xml
> +
пустая строка

2024-02-04 19:07 UTC, ievetrov commented on app/src/main/res/layout/item_method.xml
> +        android:textSize="14sp"
Тоже нужно доработать оформление

2024-02-04 19:07 UTC, ievetrov commented on app/src/main/res/layout/fragment_recipe.xml
> +        <TextView
для экрана с названием категории (шапка) лучше тоже такое применить, тк названия динамически меняются

2024-02-05 12:34 UTC, kostyasmirnov commented
![image](https://github.com/kostyasmirnov/AndroidSprint_RecipeApp/assets/105130215/e9ed1210-a27e-418b-a9ad-61addd231c16)
по поводу этого, ранее добавил в tv 
app:layout_constrainedWidth="true" и app:layout_constraintHorizontal_bias="0.0"

2024-02-07 11:56 UTC, ievetrov approved these changes

2024-02-08 08:03 UTC, merged