RA-16. Add Favorites icon and color by click
kostyasmirnov/AndroidSprint_RecipeApp pull request #16
Opened 2024-02-15 14:27 UTC by kostyasmirnov

2024-02-16 01:02 UTC, ievetrovdev requested changes

2024-02-16 01:02 UTC, ievetrovdev commented on app/src/main/java/com/practicum/androidsprint/CategoriesListFragment.kt
> +            val categories = STUB.getCategories().firstOrNull { it.id == categoryId }
эта строка разве не повторяет 49?) 49 предлагаю оставить, там находится нужная категория, далее из нее вытаскиваем заголовок и картинку

2024-02-16 01:02 UTC, ievetrovdev commented on app/src/main/java/com/practicum/androidsprint/RecipeFragment.kt
> +        var isImageFirst = true
все верно, но только в качестве временного решения

2024-02-16 01:02 UTC, ievetrovdev commented on app/src/main/java/com/practicum/androidsprint/RecipesListFragment.kt
>              }
на 69 строке тоже должна закрываться и круглая скобка

2024-02-16 01:02 UTC, ievetrovdev commented on app/src/main/java/com/practicum/androidsprint/RecipesListFragment.kt
> +            ?.let { STUB.getRecipesByCategoryId(it) }?.let { RecipesListAdapter(it, fragment = this) }
```
        val recipesListAdapter = arguments?.getInt(ARG_CATEGORY_ID)
            ?.let { STUB.getRecipesByCategoryId(it) }
            ?.let { RecipesListAdapter(it, fragment = this) }
```

2024-02-16 01:02 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipe.xml
> +            android:layout_width="40dp"
Ресурсы размеров и стили тоже выносим как обычно

2024-02-16 01:02 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipe.xml
>              tools:text="Бургеры с грибами и сыром" />
Если текст будет слишком большой, то может располагаться вплотную к правой границе или вовсе вылезет за пределы экрана. Так как мы находимся внутри констрейнта, есть пара хитрых атрибутов, чтобы это реализовать более элегантно. Не забудь добавить констрейнт справа и все протестировать
app:layout_constrainedWidth="true"
app:layout_constraintHorizontal_bias="0.0"

2024-02-26 16:08 UTC, ievetrov requested changes
и в CategoriesListFragment остался binding с оператором !!.
нужно обработать или использовать ленивую инициализацию

2024-02-26 16:08 UTC, ievetrov commented on app/src/main/java/com/practicum/androidsprint/RecipeListAdapter.kt
> +                val inputStream: InputStream? = fragment.context?.assets?.open(dataSet[position].imageUrl)
Фрагмент мы уже не передаем, тут тоже следует пофиксить

2024-02-29 21:51 UTC, ievetrovdev approved these changes

2024-02-29 21:51 UTC, ievetrovdev commented on app/src/main/java/com/practicum/androidsprint/CategoriesListAdapter.kt
>      private val context: CategoriesListFragment,
контекст/фрагмент как параметр надо совсем поубирать из всех адаптеров. мы его больше не используем

2024-03-01 11:30 UTC, merged