RA-07-Implementation-of-basic-screen-layout-with-a-list-of-categories
kostyasmirnov/AndroidSprint_RecipeApp pull request #5
Opened 2024-01-15 16:59 UTC by kostyasmirnov

2024-01-15 23:01 UTC, ievetrov requested changes
Дополнительно

- прописан стиль, но размер текста и цвет еще и в атрибутах
- есть ли тут смысл делать ширину 0? контейнер надо располагать по ширине контента (будет тот же эффект)
<img width="496" alt="Снимок экрана 2024-01-16 в 01 59 44" src="https://github.com/kostyasmirnov/AndroidSprint_RecipeApp/assets/34489023/d4000b7d-b833-493a-a3b8-3dab523485c3">

contentDescription следует дополнить, чтобы скринридеры читали "изображение экрана с категориями бургеров" или типа того

<img width="439" alt="Снимок экрана 2024-01-16 в 02 00 59" src="https://github.com/kostyasmirnov/AndroidSprint_RecipeApp/assets/34489023/96d91f7d-6622-4e03-bbc6-a020d73de2a5">

2024-01-15 23:01 UTC, ievetrov commented on app/src/main/res/layout/item_layout.xml
> +            android:contentDescription="@string/burger"
Этот дексрипшн будем проставлять уникальный для каждого айтема черед адаптер, когда будет реализован recycler view

2024-01-15 23:01 UTC, ievetrov commented on app/src/main/res/layout/item_layout.xml
> +            style="@style/StyleTitleCategories14"
проверить соответствие стилю в макете

2024-01-15 23:01 UTC, ievetrov commented on app/src/main/res/layout/item_layout.xml
> +            style="@style/StyleDescriptionCategories12"
проверить соответствие стилю в макете

2024-01-15 23:01 UTC, ievetrov commented on app/src/main/res/layout/item_layout.xml
> +            android:layout_marginStart="@dimen/main_padding_half"
Не обязательно для каждой стороны прописывать марджины по отдельности. Есть более универсальные атрибуты. 
android:layout_margin=""
android:layout_marginHorizontal=""
android:layout_marginVertical=""

2024-01-15 23:01 UTC, ievetrov commented on app/src/main/res/layout/item_layout.xml
> +    android:background="@drawable/shape_header_rounded_corners"
этот атрибут точно на что-то влияет? ты уже задаешь скругление с помощью cardCornerRadius

2024-01-15 23:01 UTC, ievetrov commented on app/src/main/res/layout/item_layout.xml
> +            android:layout_marginEnd="75dp"
Стремимся к адаптивности поэтому надо разместить контейнер на всю ширину с соответствующими отступами со всех сторон. Значение отступа, которое может меняться на разных экранах не хардкодим)

2024-01-17 19:55 UTC, kostyasmirnov commented
Потому что обсуждали в 
убрал marginEnd из `LinearLayout `, тк он не играет роли как я посмотрел 
отступ добавил в textView

2024-01-18 19:34 UTC, ievetrovdev approved these changes
1. переименовать dimens.xml 
2. в цветах появился дубль 5F3678. Повторять значения одних и тех же цветов с разными айдишниками не рекомендуется. Пусть в ресурсах хранятся только уникальные айтемы, а уникализировать значения для разных элементов интерфейса корректнее через кастомные стили.

2024-01-19 06:02 UTC, merged