RA-08-implementation-of-RecyclerView-with-a-list-of-categories
kostyasmirnov/AndroidSprint_RecipeApp pull request #6
Opened 2024-01-20 13:32 UTC by kostyasmirnov

2024-01-21 18:37 UTC, ievetrovdev requested changes
Хорошо! Еще немного про описание контента. contentDescription используется для предоставления текстового описания для не текстовых элементов, таких как изображения, кнопки с иконками и других графических объектов.
Для изображений элементов категорий тоже следует добавить описание. Причем подход  рекомендую через адаптер – чтобы у каждого элемента.было свое описание. Можно задавать картинкам категорий что-то вроде "Изображение категории название_категории".
Также для изображения экрана с категориями нужно более развернутое название.

2024-01-21 18:37 UTC, ievetrovdev commented on app/src/main/java/com/practicum/androidsprint/CategoriesListAdapter.kt
> +        val cvCategoryItem: CardView = itemView.findViewById(R.id.cvCategoryItem)
предлагаю убрать отступ при скролле. при открытии экрана все хорошо

<img width="346" alt="Снимок экрана 2024-01-21 в 21 25 30" src="https://github.com/kostyasmirnov/AndroidSprint_RecipeApp/assets/153023186/53ee199f-58b8-4c73-9f8b-d793f5b70847">

2024-01-21 18:37 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_list_categories.xml
> +    android:background="@drawable/ripple_effect"
этот компонент тут не требуется (и вероятно он никак не изменяет интерфейс сейчас).

есть простой набор атрибутов, чтобы эффект заработал
    android:foreground = "?selectableItemBackground"
    android:clickable = "true"
    android:focusable = "true"

2024-01-22 17:48 UTC, kostyasmirnov commented on app/src/main/res/layout/fragment_list_categories.xml
> +    android:background="@drawable/ripple_effect"
Все таки вернул `android:background=`@drawable/ripple_effect`
Тк при его удалении задний фон становится вот такой: 
![image](https://github.com/kostyasmirnov/AndroidSprint_RecipeApp/assets/105130215/154a2a57-4c4e-4ca5-b4e6-114683ee82e5)

2024-01-22 18:41 UTC, ievetrovdev approved these changes

2024-01-22 18:41 UTC, ievetrovdev commented on app/src/main/java/com/practicum/androidsprint/CategoriesListAdapter.kt
> +            val imageDescription = "Изображение категории ${categoryTitle.text}"
Отлично! давай в следующем ПР еще вынесем захардкоженную строку в ресурсы

2024-01-22 21:14 UTC, merged